"""
Production Google Gemini Generative AI Provider
SIH26016 Land Acquisition Platform - KOSH
Uses official google-genai SDK (v2.22+) with native async execution.
Strict Grounding, Epistemological Separation & Secret Protection Enforced.
"""
import asyncio
import json
import logging
import re
from typing import Any, Dict, List, Optional
from fastapi import HTTPException, status
from google import genai
from google.genai import types

from app.core.config import settings
from app.services.ai.prompts import ASSISTANT_SYSTEM_PROMPT, sanitize_untrusted_input
from app.services.ai.providers.base import AIProvider
from app.services.ai.schemas import (
    AIAnswer,
    AIContext,
    ChronologyItem,
    ConfidenceLevel,
    DisputeSummary,
    EvidenceRef,
    NLWhatIfScenario,
    RecommendedAction,
    SourceType,
)

logger = logging.getLogger("kosh.ai.gemini")


def _sanitize_secret(text: str, secret: str) -> str:
    """Removes API key occurrences from error strings and traces."""
    if secret and secret in text:
        return text.replace(secret, "[REDACTED_API_KEY]")
    return text


class GeminiAIProvider(AIProvider):
    """
    Production-grade generative AI provider leveraging Google Gemini models
    (e.g., gemini-3.6-flash, gemini-3.7-flash).
    Adheres strictly to the KOSH decision-support governance contract:
    - KOSH deterministic engine is the source of truth.
    - Statutory formulas and CPM numbers are never generated by LLM.
    - Epistemological separation: facts vs claims vs recommendations.
    - Untrusted inputs are sanitized and defanged.
    """

    def __init__(self, api_key: Optional[str] = None, model_name: Optional[str] = None):
        self._api_key = settings.GEMINI_API_KEY if api_key is None else api_key
        self.model_name = model_name or settings.GEMINI_MODEL or "gemini-flash-latest"
        self._active_model = self.model_name
        self._client: Optional[genai.Client] = None

        if self._api_key:
            self._client = genai.Client(api_key=self._api_key)

    @property
    def active_model_name(self) -> str:
        return self._active_model

    @property
    def is_configured(self) -> bool:
        return bool(self._api_key and self._client)

    @property
    def provider_name(self) -> str:
        return "gemini"

    def _ensure_configured(self) -> None:
        if not self.is_configured:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="AI Service Unavailable: GEMINI_API_KEY is not configured on the backend server.",
            )

    async def _generate_with_retry(
        self,
        prompt: str,
        config: types.GenerateContentConfig,
        max_retries: int = 1,
    ) -> Any:
        """Executes Gemini generate_content with bounded backoff and resilient model failover for transient 503/429 spikes."""
        candidate_models = [self._active_model]
        if "gemini-3.5-flash" not in candidate_models:
            candidate_models.append("gemini-3.5-flash")
        if self.model_name not in candidate_models:
            candidate_models.append(self.model_name)

        last_error = None
        for current_model in candidate_models:
            for attempt in range(max_retries + 1):
                try:
                    resp = await self._client.aio.models.generate_content(
                        model=current_model,
                        contents=prompt,
                        config=config,
                    )
                    self._active_model = current_model
                    return resp
                except Exception as e:
                    last_error = e
                    err_msg = _sanitize_secret(str(e), self._api_key or "")
                    is_transient = any(
                        code in err_msg
                        for code in ["429", "RESOURCE_EXHAUSTED", "503", "UNAVAILABLE", "spikes in demand"]
                    )
                    if current_model != candidate_models[-1] and is_transient:
                        logger.warning(
                            f"Model {current_model} unavailable ({err_msg[:70]}...). Seamlessly failing over to {candidate_models[-1]}..."
                        )
                        break
                    if attempt < max_retries and is_transient:
                        delay_match = re.search(r"retry in (\d+(\.\d+)?)s", err_msg, re.IGNORECASE)
                        backoff = min(float(delay_match.group(1)) + 0.5, 3.0) if delay_match else 1.5
                        logger.warning(
                            f"Transient Gemini condition on {current_model} (attempt {attempt+1}/{max_retries+1}). Retrying in {backoff:.1f}s..."
                        )
                        await asyncio.sleep(backoff)
                        continue
                    raise
        if last_error:
            raise last_error

    def _format_grounding_context(self, context: AIContext) -> str:
        """Serializes authorized AIContext into a clean, bounded XML structure."""
        ctx_dict = context.model_dump(mode="json")
        ctx_json = json.dumps(ctx_dict, indent=2, default=str)
        return f"<kosh_grounded_context>\n{ctx_json}\n</kosh_grounded_context>"

    async def generate_answer(self, context: AIContext, query: str) -> AIAnswer:
        self._ensure_configured()
        clean_query, _ = sanitize_untrusted_input(query)

        # Insufficient evidence pre-guard
        if (
            context.evidence_completeness == ConfidenceLevel.INSUFFICIENT_EVIDENCE
            or (not context.parcel_summary and not context.project_summary)
        ):
            return AIAnswer(
                query=clean_query,
                answer="Insufficient verified system evidence to answer this. The requested parcel or corridor record does not exist in the registered digital twin state.",
                confidence=ConfidenceLevel.INSUFFICIENT_EVIDENCE,
                source_refs=[],
                legal_refs=[],
                evidence_refs=[],
                recommended_actions=[],
                assumptions=[],
                unanswered_questions=["Verify parcel identifier and ensure project boundary enrollment."],
                provider="gemini",
                model=self.model_name,
                grounded=False,
                factual_basis=[],
                claims=[],
                uncertainty=["Target record not found in system state."],
            )

        grounded_context_str = self._format_grounding_context(context)

        prompt = f"""
{grounded_context_str}

USER OFFICER QUERY:
"{clean_query}"

Provide an evidence-grounded response in valid JSON matching this schema:
{{
  "answer": "Concise natural language answer explaining the situation strictly grounded in KOSH context. Never state 'The law guarantees' or invent facts.",
  "confidence": "HIGH" | "MEDIUM" | "LOW" | "INSUFFICIENT_EVIDENCE",
  "factual_basis": ["Verified system fact 1 with citation", "Verified system fact 2"],
  "claims": ["Contested assertion or complaint claim 1"],
  "recommended_actions": [
    {{
      "action_type": "ACTION_KEY",
      "title": "Short title",
      "rationale": "Why this action is needed",
      "legal_basis": "Statutory provision reference (e.g. Section 38(1))",
      "expected_effect": "Impact on schedule or risk",
      "prerequisites": ["Required condition"],
      "risk_if_not_taken": "Consequence if ignored",
      "executable": true,
      "execution_route": "/action-center"
    }}
  ],
  "uncertainty": ["Any missing record or unverified item"],
  "assumptions": ["Assumptions grounded in system state"]
}}
"""

        try:
            config = types.GenerateContentConfig(
                system_instruction=ASSISTANT_SYSTEM_PROMPT,
                temperature=0.1,
                response_mime_type="application/json",
            )
            response = await self._generate_with_retry(prompt, config)

            raw_text = response.text or "{}"
            data = json.loads(raw_text)

            # Map raw actions to RecommendedAction objects
            rec_actions = []
            for act in data.get("recommended_actions", []):
                try:
                    rec_actions.append(
                        RecommendedAction(
                            action_type=act.get("action_type", "OFFICER_REVIEW"),
                            title=act.get("title", "Officer Review"),
                            rationale=act.get("rationale", ""),
                            legal_basis=act.get("legal_basis", "RFCTLARR Act 2013"),
                            expected_effect=act.get("expected_effect", "Reduces acquisition risk"),
                            prerequisites=act.get("prerequisites", []),
                            risk_if_not_taken=act.get("risk_if_not_taken", "Statutory delay"),
                            executable=act.get("executable", True),
                            execution_route=act.get("execution_route", "/action-center"),
                            evidence_refs=[],
                        )
                    )
                except Exception:
                    pass

            # Map evidence references from context
            source_refs: List[EvidenceRef] = list(context.verified_evidence)
            legal_refs: List[str] = [ref.get("section_id", "RFCTLARR") for ref in context.legal_references]
            evidence_refs: List[EvidenceRef] = [
                r for r in source_refs if r.source_type in [SourceType.DOCUMENT, SourceType.COMPLAINT, SourceType.AWARD]
            ]

            conf_str = (data.get("confidence") or "HIGH").upper()
            try:
                conf = ConfidenceLevel(conf_str)
            except Exception:
                conf = ConfidenceLevel.HIGH

            return AIAnswer(
                query=clean_query,
                answer=data.get("answer", "Analysis completed based on registered KOSH digital twin state."),
                confidence=conf,
                source_refs=source_refs,
                legal_refs=legal_refs,
                evidence_refs=evidence_refs,
                recommended_actions=rec_actions,
                assumptions=data.get("assumptions", []),
                unanswered_questions=data.get("uncertainty", []),
                provider="gemini",
                model=self._active_model,
                grounded=True,
                factual_basis=data.get("factual_basis", []),
                claims=data.get("claims", []),
                uncertainty=data.get("uncertainty", []),
            )

        except HTTPException:
            raise
        except Exception as e:
            err_msg = _sanitize_secret(str(e), self._api_key or "")
            logger.error(f"Gemini API error during generate_answer: {err_msg}")
            if "429" in err_msg or "RESOURCE_EXHAUSTED" in err_msg:
                raise HTTPException(
                    status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                    detail=f"Gemini rate limit exceeded: {err_msg}",
                )
            if "timeout" in err_msg.lower() or "deadline" in err_msg.lower():
                raise HTTPException(
                    status_code=status.HTTP_504_GATEWAY_TIMEOUT,
                    detail=f"Gemini request timed out: {err_msg}",
                )
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Gemini generative model invocation failed: {err_msg}",
            )

    async def summarize_dispute(self, context: AIContext) -> DisputeSummary:
        self._ensure_configured()
        grounded_context_str = self._format_grounding_context(context)

        prompt = f"""
{grounded_context_str}

TASK:
Produce an evidence-grounded dispute summary for Parcel {context.parcel_id or 'Unknown'}
with strict epistemological separation between FACTS (verified system records),
CLAIMS (landowner allegations), and RECOMMENDATIONS (officer guidance).

Return valid JSON:
{{
  "title": "Title of dispute",
  "parties_involved": ["Party 1", "Party 2"],
  "facts": ["Verified system fact 1", "Verified system fact 2"],
  "interpretations": ["Claimant assertion 1"],
  "recommendations": ["Recommended administrative action 1"],
  "chronology": [
    {{
      "date": "YYYY-MM-DD",
      "event": "Description of event"
    }}
  ],
  "compensation_status": "PENDING | DISPUTED | APPROVED | PAID",
  "statutory_clock_status": "Summary of limitation deadlines",
  "cpm_float_impact": "Summary of critical path float impact",
  "missing_evidence_checklist": ["Missing evidentiary item 1"],
  "applicable_legal_provisions": ["Section 38", "Section 64"]
}}
"""

        try:
            config = types.GenerateContentConfig(
                system_instruction=ASSISTANT_SYSTEM_PROMPT,
                temperature=0.1,
                response_mime_type="application/json",
            )
            response = await self._generate_with_retry(prompt, config)

            data = json.loads(response.text or "{}")

            chronology_items = []
            for ch in data.get("chronology", []):
                chronology_items.append(
                    ChronologyItem(
                        date=ch.get("date", "Unknown"),
                        event=ch.get("event", "Recorded event"),
                    )
                )

            return DisputeSummary(
                dispute_id=f"DISPUTE-{context.parcel_id or 'GEN'}",
                parcel_id=context.parcel_id,
                project_id=context.project_id or "P-NH927A",
                title=data.get("title", f"Dispute Summary for Parcel {context.parcel_id}"),
                parties_involved=data.get("parties_involved", ["Landowner / Interested Person", "NHAI Competent Authority"]),
                facts=data.get("facts", ["Verified parcel record loaded in digital twin."]),
                interpretations=data.get("interpretations", []),
                recommendations=data.get("recommendations", []),
                chronology=chronology_items,
                compensation_status=data.get("compensation_status", "DISPUTED"),
                statutory_clock_status=data.get("statutory_clock_status", "Section 19(7) / Section 25 clocks active"),
                cpm_float_impact=data.get("cpm_float_impact", "0 days schedule float on critical corridor chain"),
                verified_documents=[r for r in context.verified_evidence if r.source_type == SourceType.DOCUMENT],
                missing_evidence_checklist=data.get("missing_evidence_checklist", []),
                applicable_legal_provisions=data.get("applicable_legal_provisions", ["Section 38", "Section 64"]),
            )

        except HTTPException:
            raise
        except Exception as e:
            err_msg = _sanitize_secret(str(e), self._api_key or "")
            logger.error(f"Gemini API error during summarize_dispute: {err_msg}")
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Gemini dispute summarization failed: {err_msg}",
            )

    async def recommend_actions(self, context: AIContext) -> List[RecommendedAction]:
        self._ensure_configured()
        grounded_context_str = self._format_grounding_context(context)

        prompt = f"""
{grounded_context_str}

TASK:
Identify permissible administrative officer actions to resolve bottlenecks or compliance risks
on Parcel {context.parcel_id or 'Target'}.
Return valid JSON:
[
  {{
    "action_type": "PROCESS_COMPENSATION | DGPS_SURVEY | ISSUE_HEARING_NOTICE | EXPEDITE_AWARD",
    "title": "Action title",
    "rationale": "Why needed",
    "legal_basis": "Specific RFCTLARR Section from context",
    "expected_effect": "Schedule recovery or compliance assurance",
    "prerequisites": ["Condition 1"],
    "risk_if_not_taken": "Consequence",
    "executable": true,
    "execution_route": "/action-center"
  }}
]
"""

        try:
            config = types.GenerateContentConfig(
                system_instruction=ASSISTANT_SYSTEM_PROMPT,
                temperature=0.1,
                response_mime_type="application/json",
            )
            response = await self._generate_with_retry(prompt, config)

            data = json.loads(response.text or "[]")
            if not isinstance(data, list):
                data = [data]

            actions = []
            for act in data:
                actions.append(
                    RecommendedAction(
                        action_type=act.get("action_type", "OFFICER_REVIEW"),
                        title=act.get("title", "Statutory Review"),
                        rationale=act.get("rationale", "Ensure procedural compliance"),
                        legal_basis=act.get("legal_basis", "RFCTLARR Act 2013"),
                        expected_effect=act.get("expected_effect", "Mitigates acquisition bottleneck"),
                        prerequisites=act.get("prerequisites", []),
                        risk_if_not_taken=act.get("risk_if_not_taken", "Statutory delay"),
                        executable=act.get("executable", True),
                        execution_route=act.get("execution_route", "/action-center"),
                        evidence_refs=[],
                    )
                )
            return actions

        except HTTPException:
            raise
        except Exception as e:
            err_msg = _sanitize_secret(str(e), self._api_key or "")
            logger.error(f"Gemini API error during recommend_actions: {err_msg}")
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Gemini action recommendation failed: {err_msg}",
            )

    async def parse_whatif_scenario(self, query: str, context: AIContext) -> NLWhatIfScenario:
        self._ensure_configured()
        clean_query, _ = sanitize_untrusted_input(query)

        prompt = f"""
Translate this natural language scenario question into deterministic What-If simulator parameters:
QUERY: "{clean_query}"
TARGET PARCEL: "{context.parcel_id or 'P00001'}"

Supported interventions in KOSH:
- process_compensation: clears compensation dispute and enables award payment
- expedite_award: compresses Section 23/25 award timeline
- resolve_dispute: reconciles title contestation or boundary clash
- court_stay_vacated: clears judicial stay

Return valid JSON:
{{
  "is_supported": true | false,
  "unsupported_reason": null or "reason if not supported",
  "intervention_type": "process_compensation" | "expedite_award" | "resolve_dispute" | "court_stay_vacated",
  "target_entity_ids": ["P00001"],
  "acceleration_factor": 1.0,
  "parsed_intent": "Brief description of interpreted scenario"
}}
"""

        try:
            config = types.GenerateContentConfig(
                system_instruction=ASSISTANT_SYSTEM_PROMPT,
                temperature=0.0,
                response_mime_type="application/json",
            )
            response = await self._generate_with_retry(prompt, config)

            data = json.loads(response.text or "{}")
            return NLWhatIfScenario(
                raw_query=clean_query,
                is_supported=data.get("is_supported", True),
                unsupported_reason=data.get("unsupported_reason"),
                intervention_type=data.get("intervention_type", "process_compensation"),
                target_entity_ids=data.get("target_entity_ids") or [context.parcel_id or "P00001"],
                acceleration_factor=float(data.get("acceleration_factor", 1.0)),
                parsed_intent=data.get("parsed_intent", "Simulate intervention on target parcel"),
            )

        except HTTPException:
            raise
        except Exception as e:
            err_msg = _sanitize_secret(str(e), self._api_key or "")
            logger.error(f"Gemini API error during parse_whatif_scenario: {err_msg}")
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"Gemini What-If parsing failed: {err_msg}",
            )

    async def explain_whatif_result(self, scenario: NLWhatIfScenario, result: Dict[str, Any]) -> str:
        self._ensure_configured()
        before = result.get("before", {})
        after = result.get("after", {})
        delay_reduction = result.get("delay_reduction_days", 0)

        prompt = f"""
EXACT DETERMINISTIC SIMULATION METRICS (SOURCE OF TRUTH):
- Scenario: {scenario.parsed_intent}
- Target: {scenario.target_entity_ids}
- Baseline Corridor Delay: {before.get('project_delay_days', 0)} days
- Counterfactual Corridor Delay: {after.get('project_delay_days', 0)} days
- Modeled Delay Reduction: {delay_reduction} days
- Critical Path Shift: from {len(before.get('critical_path', []))} nodes to {len(after.get('critical_path', []))} nodes

TASK:
Explain this simulation result in 2-3 clear, professional sentences for a highway project director.
CRITICAL CONSTRAINT: You MUST state the EXACT numbers provided above ({delay_reduction} days reduction).
NEVER calculate or invent new numerical figures.
"""

        try:
            config = types.GenerateContentConfig(
                system_instruction=ASSISTANT_SYSTEM_PROMPT,
                temperature=0.1,
            )
            response = await self._generate_with_retry(prompt, config)
            return (response.text or "").strip()

        except HTTPException:
            raise
        except Exception as e:
            err_msg = _sanitize_secret(str(e), self._api_key or "")
            logger.error(f"Gemini API error during explain_whatif_result: {err_msg}")
            return (
                f"Under the registered CPM dependency model, executing {scenario.parsed_intent} "
                f"reduces overall corridor delay by {delay_reduction} days "
                f"(from {before.get('project_delay_days', 0)} to {after.get('project_delay_days', 0)} days)."
            )
