import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type LanguageCode =
  | "en"
  | "hi"
  | "bn"
  | "mr"
  | "te"
  | "ta"
  | "kn"
  | "ml"
  | "gu"
  | "or"
  | "pa"
  | "bho"
  | "mai";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  speechCode: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", speechCode: "hi-IN" },
  { code: "en", name: "English", nativeName: "English", speechCode: "en-IN" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", speechCode: "bn-IN" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", speechCode: "mr-IN" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", speechCode: "te-IN" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", speechCode: "ta-IN" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", speechCode: "kn-IN" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", speechCode: "ml-IN" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", speechCode: "gu-IN" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ", speechCode: "or-IN" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", speechCode: "pa-IN" },
  { code: "bho", name: "Bhojpuri", nativeName: "भोजपुरी", speechCode: "hi-IN" },
  { code: "mai", name: "Maithili", nativeName: "मैथिली", speechCode: "hi-IN" },
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav & Shell
    "nav.home": "Home",
    "nav.dashboard": "Overview",
    "nav.transactions": "Transactions",
    "nav.record": "Record Entry",
    "nav.loans": "Loans",
    "nav.members": "Members",
    "nav.approvals": "Approvals",
    "nav.meeting": "Meeting Session",
    "nav.cashCheck": "Cash Check",
    "nav.paperImport": "Paper Import",
    "nav.verification": "Verification",
    "nav.disputes": "Disputes",
    "nav.reports": "Reports",
    "nav.timeline": "Financial Timeline",
    "nav.passbook": "Member Passbook",
    "nav.sync": "Offline Sync",
    "nav.settings": "Settings",
    "nav.audit": "Audit History",
    "nav.panchasutra": "Panchasutra Health",
    "nav.bankPosition": "Bank & Cash",
    "nav.signOut": "Sign Out",
    "nav.viewAs": "View As",

    // Titles & Subtitles
    "app.title": "Lekha",
    "app.groupName": "Maa Durga SHG",
    "app.location": "Varanasi, Uttar Pradesh",

    // Common Actions
    "action.confirm": "Confirm & Save",
    "action.cancel": "Cancel",
    "action.continue": "Continue",
    "action.back": "Back",
    "action.submit": "Submit",
    "action.addTransaction": "+ Add Transaction",
    "action.createLoan": "Apply for Loan",
    "action.repay": "Record Repayment",
    "action.viewLedger": "View Ledger",
    "action.print": "Print Receipt",
    "action.verify": "Verify Cryptography",
    "action.closeMeeting": "Close & Seal Meeting",
    "action.speak": "Audio Playback",

    // Financial Totals
    "fin.totalCorpus": "Total Group Corpus",
    "fin.balance": "Current Balance",
    "fin.totalContributions": "Total Contributions",
    "fin.activeLoans": "Active Loans",
    "fin.outstandingLoans": "Outstanding Loans",
    "fin.verifiedRecords": "Verified Records",
    "fin.physicalCash": "Physical Cash in Hand",
    "fin.bankBalance": "Bank Balance",
    "fin.reconciled": "Reconciled",
    "fin.savingsCollected": "Savings Collected",

    // Categories
    "cat.contribution": "Regular Savings",
    "cat.loan": "Internal Loan",
    "cat.repayment": "Loan Repayment",
    "cat.expense": "Group Expense",

    // Roles
    "role.member": "Member",
    "role.treasurer": "Treasurer",
    "role.auditor": "Federation Auditor",
    "role.leader": "Group Leader",

    // Statuses
    "status.verified": "Verified",
    "status.pending": "Pending",
    "status.underReview": "Under Review",
    "status.cleared": "Cleared",
    "status.overdue": "Overdue",
    "status.matched": "Matched (₹0 Delta)",
    "status.mismatch": "Mismatch",
    "status.closed": "Certified & Closed",
  },

  hi: {
    // Nav & Shell
    "nav.home": "मुख्य पृष्ठ",
    "nav.dashboard": "अवलोकन",
    "nav.transactions": "लेन-देन सूची",
    "nav.record": "आवाज़ से प्रविष्टि",
    "nav.loans": "ऋण (लोन)",
    "nav.members": "सदस्य",
    "nav.approvals": "स्वीकृतियां",
    "nav.meeting": "बैठक सत्र",
    "nav.cashCheck": "रोकड़ मिलान (कैश)",
    "nav.paperImport": "रजिस्टर आयात",
    "nav.verification": "सत्यापन व जांच",
    "nav.disputes": "शिकायत व विवाद",
    "nav.reports": "वित्तीय रिपोर्ट",
    "nav.timeline": "वित्तीय टाइमलाइन",
    "nav.passbook": "पासबुक",
    "nav.sync": "ऑफ़लाइन सिंक",
    "nav.settings": "सेटिंग्स",
    "nav.audit": "ऑडिट इतिहास",
    "nav.panchasutra": "पंचसूत्र स्वास्थ्य",
    "nav.bankPosition": "बैंक व रोकड़",
    "nav.signOut": "लॉग आउट",
    "nav.viewAs": "भूमिका बदलें",

    // Titles & Subtitles
    "app.title": "लेखा (Lekha)",
    "app.groupName": "माँ दुर्गा स्वयं सहायता समूह",
    "app.location": "वाराणसी, उत्तर प्रदेश",

    // Common Actions
    "action.confirm": "पुष्टि करें और सहेजें",
    "action.cancel": "रद्द करें",
    "action.continue": "आगे बढ़ें",
    "action.back": "पीछे जाएं",
    "action.submit": "जमा करें",
    "action.addTransaction": "+ नया लेन-देन",
    "action.createLoan": "ऋण आवेदन",
    "action.repay": "किस्त जमा करें",
    "action.viewLedger": "बहीखाता देखें",
    "action.print": "रसीद प्रिंट करें",
    "action.verify": "सुरक्षा जांचें",
    "action.closeMeeting": "बैठक समाप्त व प्रमाणित करें",
    "action.speak": "आवाज़ में सुनें",

    // Financial Totals
    "fin.totalCorpus": "कुल समूह कोष",
    "fin.balance": "वर्तमान शेष",
    "fin.totalContributions": "कुल बचत योगदान",
    "fin.activeLoans": "सक्रिय ऋण",
    "fin.outstandingLoans": "बकाया ऋण राशि",
    "fin.verifiedRecords": "सत्यापित रिकॉर्ड",
    "fin.physicalCash": "हाथ में नकद (कैश)",
    "fin.bankBalance": "बैंक खाता शेष",
    "fin.reconciled": "पूर्ण मिलान",
    "fin.savingsCollected": "सत्र में एकत्रित बचत",

    // Categories
    "cat.contribution": "नियमित बचत",
    "cat.loan": "समूह ऋण",
    "cat.repayment": "ऋण वापसी/किस्त",
    "cat.expense": "समूह खर्च",

    // Roles
    "role.member": "सदस्य",
    "role.treasurer": "कोषाध्यक्ष",
    "role.auditor": "फेडरेशन ऑडिटर",
    "role.leader": "समूह अध्यक्ष/लीडर",

    // Statuses
    "status.verified": "सत्यापित",
    "status.pending": "लंबित",
    "status.underReview": "जांच जारी",
    "status.cleared": "पूर्ण चुकता",
    "status.overdue": "अतिदेय (विलंबित)",
    "status.matched": "सटीक मिलान (₹0 अंतर)",
    "status.mismatch": "अंतर मौजूद",
    "status.closed": "प्रमाणित व बंद",
  },

  bn: {
    "nav.home": "হোম",
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.transactions": "লেনদেন",
    "nav.record": "ভয়েস এন্ট্রি",
    "nav.loans": "ঋণ",
    "nav.members": "সদস্যগণ",
    "nav.approvals": "অনুমোদন",
    "nav.meeting": "মিটিং সেশন",
    "nav.cashCheck": "ক্যাশ যাচাই",
    "nav.paperImport": "রেজিস্টার ইম্পোর্ট",
    "nav.verification": "ভেরিফিকেশন",
    "nav.disputes": "অভিযোগ",
    "nav.reports": "রিপোর্ট",
    "nav.timeline": "টাইমলাইন",
    "nav.passbook": "পাসবুক",
    "nav.sync": "অফলাইন সিঙ্ক",
    "nav.settings": "সেটিংস",
    "nav.audit": "অডিট ইতিহাস",
    "nav.panchasutra": "পঞ্চসূত্র স্বাস্থ্য",
    "nav.bankPosition": "ব্যাংক ও ক্যাশ",
    "nav.signOut": "লগআউট",
    "nav.viewAs": "ভূমিকা পরিবর্তন",
    "app.title": "লেখা (Lekha)",
    "app.groupName": "মা দুর্গা এসএইচজি",
    "app.location": "বারাণসী, উত্তর প্রদেশ",
    "action.confirm": "নিশ্চিত করুন ও সংরক্ষণ করুন",
    "action.cancel": "বাতিল",
    "action.continue": "পরবর্তী",
    "action.back": "পেছনে",
    "action.submit": "জমা দিন",
    "action.addTransaction": "+ নতুন লেনদেন",
    "action.createLoan": "ঋণের আবেদন",
    "action.repay": "কিস্তি পরিশোধ",
    "action.viewLedger": "লেজার দেখুন",
    "action.print": "রসিদ প্রিন্ট",
    "action.verify": "যাচাই করুন",
    "action.closeMeeting": "মিটিং সমাপ্ত করুন",
    "action.speak": "শুনুন",
    "fin.totalCorpus": "মোট তহবিল",
    "fin.balance": "বর্তমান স্থিতি",
    "fin.totalContributions": "মোট সঞ্চয়",
    "fin.activeLoans": "চলতি ঋণ",
    "fin.outstandingLoans": "বকেয়া ঋণ",
    "fin.verifiedRecords": "যাচাইকৃত রেকর্ড",
    "fin.physicalCash": "নগদ টাকা",
    "fin.bankBalance": "ব্যাংক স্থিতি",
    "fin.reconciled": "সমন্বিত",
    "fin.savingsCollected": "সংগৃহীত সঞ্চয়",
    "cat.contribution": "নিয়মিত সঞ্চয়",
    "cat.loan": "অভ্যন্তরীণ ঋণ",
    "cat.repayment": "ঋণ পরিশোধ",
    "cat.expense": "গ্রুপের খরচ",
    "role.member": "সদস্য",
    "role.treasurer": "কোষাধ্যক্ষ",
    "role.auditor": "অডিটর",
    "role.leader": "দলনেত্রী",
    "status.verified": "যাচাইকৃত",
    "status.pending": "মুলতুবি",
    "status.underReview": "পর্যালোচনাধীন",
    "status.cleared": "পরিশোধিত",
    "status.overdue": "বকেয়া",
    "status.matched": "মিল সম্পন্ন",
    "status.mismatch": "পার্থক্য আছে",
    "status.closed": "বন্ধ",
  },

  mr: {
    "nav.home": "मुख्यपृष्ठ",
    "nav.dashboard": "आढावा",
    "nav.transactions": "व्यवहार यादी",
    "nav.record": "आवाज नोंदणी",
    "nav.loans": "कर्ज",
    "nav.members": "सदस्य",
    "nav.approvals": "मंजुरी",
    "nav.meeting": "बैठक",
    "nav.cashCheck": "रोख पडताळणी",
    "nav.paperImport": "नोंदवही आयात",
    "nav.verification": "पडताळणी",
    "nav.disputes": "तक्रारी",
    "nav.reports": "अहवाल",
    "nav.timeline": "आर्थिक टाइमलाइन",
    "nav.passbook": "पासबुक",
    "nav.sync": "ऑफलाइन सिंक",
    "nav.settings": "सेटिंग्ज",
    "nav.audit": "ऑडिट इतिहास",
    "nav.panchasutra": "पंचसूत्र",
    "nav.bankPosition": "बँक व रोख",
    "nav.signOut": "बाहेर पडा",
    "nav.viewAs": "भूमिका निवडा",
    "app.title": "लेखा (Lekha)",
    "app.groupName": "माँ दुर्गा बचत गट",
    "app.location": "वाराणसी, उत्तर प्रदेश",
    "action.confirm": "निश्चित करा आणि जतन करा",
    "action.cancel": "रद्द करा",
    "action.continue": "पुढे चला",
    "action.back": "मागे",
    "action.submit": "सबमिट करा",
    "action.addTransaction": "+ नवीन व्यवहार",
    "action.createLoan": "कर्ज अर्ज",
    "action.repay": "हप्ता जमा करा",
    "action.viewLedger": "खातेवही पहा",
    "action.print": "पावती छापा",
    "action.verify": "तपासा",
    "action.closeMeeting": "बैठक पूर्ण करा",
    "action.speak": "ऐका",
    "fin.totalCorpus": "एकूण निधी",
    "fin.balance": "सध्याची शिल्लक",
    "fin.totalContributions": "एकूण बचत",
    "fin.activeLoans": "सक्रिय कर्ज",
    "fin.outstandingLoans": "थकबाकी",
    "fin.verifiedRecords": "तपासलेल्या नोंदी",
    "fin.physicalCash": "हातातील रोख रक्कम",
    "fin.bankBalance": "बँक शिल्लक",
    "fin.reconciled": "जुळवणी झाली",
    "fin.savingsCollected": "जमा झालेली बचत",
    "cat.contribution": "नियमित बचत",
    "cat.loan": "अंतर्गत कर्ज",
    "cat.repayment": "कर्ज परतफेड",
    "cat.expense": "गटाचा खर्च",
    "role.member": "सदस्य",
    "role.treasurer": "खजिनदार",
    "role.auditor": "लेखापरीक्षक",
    "role.leader": "अध्यक्ष/नेते",
    "status.verified": "तपासलेले",
    "status.pending": "प्रलंबित",
    "status.underReview": "तपासणी सुरू",
    "status.cleared": "पूर्ण भरले",
    "status.overdue": "थकीत",
    "status.matched": "तंतोतंत जुळले",
    "status.mismatch": "तफावत",
    "status.closed": "बंद",
  },

  te: {
    "nav.home": "హోమ్",
    "nav.dashboard": "సమీక్ష",
    "nav.transactions": "లావాదేవీలు",
    "nav.record": "వాయిస్ ఎంట్రీ",
    "nav.loans": "రుణాలు",
    "nav.members": "సభ్యులు",
    "nav.approvals": "ఆమోదాలు",
    "nav.meeting": "సమావేశం",
    "nav.cashCheck": "నగదు తనిఖీ",
    "nav.paperImport": "రిజిస్టర్ దిగుమతి",
    "nav.verification": "ధృవీకరణ",
    "nav.disputes": "ఫిర్యాదులు",
    "nav.reports": "నివేదికలు",
    "nav.timeline": "టైమ్‌లైన్",
    "nav.passbook": "పాస్‌బుక్",
    "nav.sync": "ఆఫ్‌లైన్ సమకాలీకరణ",
    "nav.settings": "సెట్టింగ్‌లు",
    "nav.audit": "ఆడిట్ చరిత్ర",
    "nav.panchasutra": "పంచసూత్రాలు",
    "nav.bankPosition": "బ్యాంకు & నగదు",
    "nav.signOut": "లాగ్ అవుట్",
    "nav.viewAs": "పాత్ర మార్చు",
    "app.title": "లేఖ (Lekha)",
    "app.groupName": "మా దుర్గా SHG",
    "app.location": "వారణాసి, ఉత్తరప్రదేశ్",
    "action.confirm": "నిర్ధారించి భద్రపరచు",
    "action.cancel": "రద్దు",
    "action.continue": "కొనసాగించు",
    "action.back": "వెనుకకు",
    "action.submit": "సమర్పించు",
    "action.addTransaction": "+ కొత్త లావాదేవీ",
    "action.createLoan": "రుణం దరఖాస్తు",
    "action.repay": "వాయిదా చెల్లింపు",
    "action.viewLedger": "లెడ్జర్ చూడండి",
    "action.print": "రశీదు ముద్రించు",
    "action.verify": "ధృవీకరించు",
    "action.closeMeeting": "సమావేశం ముగించు",
    "action.speak": "వినండి",
    "fin.totalCorpus": "మొత్తం నిధి",
    "fin.balance": "ప్రస్తుత నిల్వ",
    "fin.totalContributions": "మొత్తం పొదుపు",
    "fin.activeLoans": "ప్రస్తుత రుణాలు",
    "fin.outstandingLoans": "బకాయి రుణాలు",
    "fin.verifiedRecords": "ధృవీకరించిన రికార్డులు",
    "fin.physicalCash": "చేతిలో ఉన్న నగదు",
    "fin.bankBalance": "బ్యాంక్ నిల్వ",
    "fin.reconciled": "సరిపోలింది",
    "fin.savingsCollected": "సేకరించిన పొదుపు",
    "cat.contribution": "సాధారణ పొదుపు",
    "cat.loan": "రుణం",
    "cat.repayment": "రుణ తిరిగి చెల్లింపు",
    "cat.expense": "ఖర్చులు",
    "role.member": "సభ్యురాలు",
    "role.treasurer": "కోశాధికారి",
    "role.auditor": "ఆడిటర్",
    "role.leader": "గ్రూప్ లీడర్",
    "status.verified": "ధృవీకరించబడింది",
    "status.pending": "పెండింగ్‌లో ఉంది",
    "status.underReview": "సమీక్షలో ఉంది",
    "status.cleared": "పూర్తిగా చెల్లించబడింది",
    "status.overdue": "గడువు ముగిసింది",
    "status.matched": "సరిగ్గా సరిపోలింది",
    "status.mismatch": "తేడా ఉంది",
    "status.closed": "ముగిసింది",
  },

  ta: {
    "nav.home": "முகப்பு",
    "nav.dashboard": "கண்ணோட்டம்",
    "nav.transactions": "பரிவர்த்தனைகள்",
    "nav.record": "குரல் பதிவு",
    "nav.loans": "கடன்கள்",
    "nav.members": "உறுப்பினர்கள்",
    "nav.approvals": "ஒப்புதல்கள்",
    "nav.meeting": "கூட்டம்",
    "nav.cashCheck": "பண சரிபார்ப்பு",
    "nav.paperImport": "பதிவேடு இறக்குமதி",
    "nav.verification": "சரிபார்ப்பு",
    "nav.disputes": "புகார்கள்",
    "nav.reports": "அறிக்கைகள்",
    "nav.timeline": "காலவரிசை",
    "nav.passbook": "பாஸ்புக்",
    "nav.sync": "ஆஃப்லைன் ஒத்திசைவு",
    "nav.settings": "அமைப்புகள்",
    "nav.audit": "தணிக்கை வரலாறு",
    "nav.panchasutra": "பஞ்சசூத்திரம்",
    "nav.bankPosition": "வங்கி & பணம்",
    "nav.signOut": "வெளியேறு",
    "nav.viewAs": "பொறுப்பு மாற்று",
    "app.title": "லேகா (Lekha)",
    "app.groupName": "மா துர்கா சுயஉதவிக்குழு",
    "app.location": "வாரணாசி, உ.பி",
    "action.confirm": "உறுதி செய்து சேமி",
    "action.cancel": "ரத்து செய்",
    "action.continue": "தொடரவும்",
    "action.back": "பின்செல்",
    "action.submit": "சமர்ப்பி",
    "action.addTransaction": "+ புதிய பரிவர்த்தனை",
    "action.createLoan": "கடன் விண்ணப்பம்",
    "action.repay": "தவணை செலுத்து",
    "action.viewLedger": "கணக்கை பார்க்க",
    "action.print": "ரசீது அச்சிடு",
    "action.verify": "சரிபார்",
    "action.closeMeeting": "கூட்டத்தை முடிக்கவும்",
    "action.speak": "கேட்கவும்",
    "fin.totalCorpus": "மொத்த நிதி",
    "fin.balance": "தற்போதைய இருப்பு",
    "fin.totalContributions": "மொத்த சேமிப்பு",
    "fin.activeLoans": "நடப்பு கடன்கள்",
    "fin.outstandingLoans": "நிலுவை கடன்",
    "fin.verifiedRecords": "சரிபார்க்கப்பட்டவை",
    "fin.physicalCash": "கைவசம் உள்ள ரொக்கம்",
    "fin.bankBalance": "வங்கி இருப்பு",
    "fin.reconciled": "சரிசெய்யப்பட்டது",
    "fin.savingsCollected": "சேகரிக்கப்பட்ட தொகை",
    "cat.contribution": "வழக்கமான சேமிப்பு",
    "cat.loan": "உள் கடன்",
    "cat.repayment": "கடன் திருப்பிச் செலுத்துதல்",
    "cat.expense": "குழு செலவு",
    "role.member": "உறுப்பினர்",
    "role.treasurer": "பொருளாளர்",
    "role.auditor": "தணிக்கையாளர்",
    "role.leader": "தலைவர்",
    "status.verified": "சரிபார்க்கப்பட்டது",
    "status.pending": "நிலுவையில்",
    "status.underReview": "ஆய்வில் உள்ளது",
    "status.cleared": "முழுமையாக செலுத்தப்பட்டது",
    "status.overdue": "தவணை தாண்டியது",
    "status.matched": "பொருந்தியது",
    "status.mismatch": "முரண்பாடு",
    "status.closed": "முடிக்கப்பட்டது",
  },

  kn: {
    "nav.home": "ಮುಖಪುಟ",
    "nav.dashboard": "ಅವಲೋಕನ",
    "nav.transactions": "ವಹಿವಾಟುಗಳು",
    "nav.record": "ಧ್ವನಿ ನಮೂದು",
    "nav.loans": "ಸಾಲಗಳು",
    "nav.members": "ಸದಸ್ಯರು",
    "nav.approvals": "ಅನುಮೋದನೆಗಳು",
    "nav.meeting": "ಸಭೆಯ ಅಧಿವೇಶನ",
    "nav.cashCheck": "ನಗದು ಪರಿಶೀಲನೆ",
    "nav.paperImport": "ರಿಜಿಸ್ಟರ್ ಆಮದು",
    "nav.verification": "ಪರಿಶೀಲನೆ",
    "nav.disputes": "ದೂರುಗಳು",
    "nav.reports": "ವರದಿಗಳು",
    "nav.timeline": "ಟೈಮ್‌ಲೈನ್",
    "nav.passbook": "ಪಾಸ್‌ಬುಕ್",
    "nav.sync": "ಆಫ್‌ಲೈನ್ ಸಿಂಕ್",
    "nav.settings": "ಸೆಟ್ಟಿಂಗ್ಸ್",
    "nav.audit": "ಆಡಿಟ್ ಇತಿಹಾಸ",
    "nav.panchasutra": "ಪಂಚಸೂತ್ರ",
    "nav.bankPosition": "ಬ್ಯಾಂಕ್ ಮತ್ತು ನಗದು",
    "nav.signOut": "ಲಾಗ್ ಔಟ್",
    "nav.viewAs": "ಪಾತ್ರ ಬದಲಿಸಿ",
    "app.title": "ಲೇಖಾ (Lekha)",
    "app.groupName": "ಮಾ ದುರ್ಗಾ ಎಸ್ಎಚ್‌ಜಿ",
    "app.location": "ವಾರಣಾಸಿ, ಯುಪಿ",
    "action.confirm": "ದೃಢೀಕರಿಸಿ ಮತ್ತು ಉಳಿಸಿ",
    "action.cancel": "ರದ್ದುಮಾಡಿ",
    "action.continue": "ಮುಂದುವರಿಸಿ",
    "action.back": "ಹಿಂದಕ್ಕೆ",
    "action.submit": "ಸಲ್ಲಿಸಿ",
    "action.addTransaction": "+ ಹೊಸ ವಹಿವಾಟು",
    "action.createLoan": "ಸಾಲಕ್ಕಾಗಿ ಅರ್ಜಿ",
    "action.repay": "ಮರುಪಾವತಿ",
    "action.viewLedger": "ಲೆಡ್ಜರ್ ವೀಕ್ಷಿಸಿ",
    "action.print": "ರಶೀದಿ ಮುದ್ರಿಸಿ",
    "action.verify": "ದೃಢೀಕರಿಸಿ",
    "action.closeMeeting": "ಸಭೆಯನ್ನು ಮುಕ್ತಾಯಗೊಳಿಸಿ",
    "action.speak": "ಆಲಿಸಿ",
    "fin.totalCorpus": "ಒಟ್ಟು ನಿಧಿ",
    "fin.balance": "ಪ್ರಸ್ತುತ ಬಾಕಿ",
    "fin.totalContributions": "ಒಟ್ಟು ಉಳಿತಾಯ",
    "fin.activeLoans": "ಸಕ್ರಿಯ ಸಾಲಗಳು",
    "fin.outstandingLoans": "ಬಾಕಿ ಸಾಲ",
    "fin.verifiedRecords": "ಪರಿಶೀಲಿಸಿದ ದಾಖಲೆಗಳು",
    "fin.physicalCash": "ಕೈಯಲ್ಲಿರುವ ನಗದು",
    "fin.bankBalance": "ಬ್ಯಾಂಕ್ ಬಾಕಿ",
    "fin.reconciled": "ಹೊಂದಾಣಿಕೆಯಾಗಿದೆ",
    "fin.savingsCollected": "ಸಂಗ್ರಹಿಸಿದ ಉಳಿತಾಯ",
    "cat.contribution": "ನಿಯಮಿತ ಉಳಿತಾಯ",
    "cat.loan": "ಆಂತರಿಕ ಸಾಲ",
    "cat.repayment": "ಸಾಲ ಮರುಪಾವತಿ",
    "cat.expense": "ಗುಂಪಿನ ವೆಚ್ಚ",
    "role.member": "ಸದಸ್ಯೆ",
    "role.treasurer": "ಖಜಾಂಚಿ",
    "role.auditor": "ಆಡಿಟರ್",
    "role.leader": "ಗುಂಪು ನಾಯಕಿ",
    "status.verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    "status.pending": "ಬಾಕಿ ಇದೆ",
    "status.underReview": "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ",
    "status.cleared": "ಪಾವತಿಸಲಾಗಿದೆ",
    "status.overdue": "ಮೀರಿದ ಅವಧಿ",
    "status.matched": "ಹೊಂದಿಕೆಯಾಗಿದೆ",
    "status.mismatch": "ವ್ಯತ್ಯಾಸವಿದೆ",
    "status.closed": "ಮುಕ್ತಾಯವಾಗಿದೆ",
  },

  ml: {
    "nav.home": "ഹോം",
    "nav.dashboard": "അവലോകനം",
    "nav.transactions": "ഇടപാടുകൾ",
    "nav.record": "വോയ്സ് എൻട്രി",
    "nav.loans": "വായ്പകൾ",
    "nav.members": "അംഗങ്ങൾ",
    "nav.approvals": "അംഗീകാരങ്ങൾ",
    "nav.meeting": "യോഗം",
    "nav.cashCheck": "പണ പരിശോധന",
    "nav.paperImport": "രജിസ്റ്റർ ഇറക്കുമതി",
    "nav.verification": "സ്ഥിരീകരണം",
    "nav.disputes": "പരാതികൾ",
    "nav.reports": "റിപ്പോർട്ടുകൾ",
    "nav.timeline": "ടൈംലൈൻ",
    "nav.passbook": "പാസ്ബുക്ക്",
    "nav.sync": "ഓഫ്‌ലൈൻ സമന്വയം",
    "nav.settings": "ക്രമീകരണങ്ങൾ",
    "nav.audit": "ഓഡിറ്റ് ചരിത്രം",
    "nav.panchasutra": "പഞ്ചസൂത്ര",
    "nav.bankPosition": "ബാങ്ക് & പണം",
    "nav.signOut": "ലോഗ് ഔട്ട്",
    "nav.viewAs": "റോൾ മാറ്റുക",
    "app.title": "ലേഖ (Lekha)",
    "app.groupName": "മാ ദുർഗ്ഗാ എസ്.എച്ച്.ജി",
    "app.location": "വാരണാസി",
    "action.confirm": "സ്ഥിരീകരിച്ച് സംരക്ഷിക്കുക",
    "action.cancel": "റദ്ദാക്കുക",
    "action.continue": "തുടരുക",
    "action.back": "തിരികെ",
    "action.submit": "സമർപ്പിക്കുക",
    "action.addTransaction": "+ പുതിയ ഇടപാട്",
    "action.createLoan": "വായ്പ അപേക്ഷ",
    "action.repay": "തിരിച്ചടവ്",
    "action.viewLedger": "ലെഡ്ജർ കാണുക",
    "action.print": "രസീത് പ്രിന്റ് ചെയ്യുക",
    "action.verify": "പരിശോധിക്കുക",
    "action.closeMeeting": "യോഗം അവസാനിപ്പിക്കുക",
    "action.speak": "കേൾക്കുക",
    "fin.totalCorpus": "ആകെ ഫണ്ട്",
    "fin.balance": "നിലവിലെ നീക്കിയിരിപ്പ്",
    "fin.totalContributions": "ആകെ നിക്ഷേപം",
    "fin.activeLoans": "നടപ്പിലുള്ള വായ്പകൾ",
    "fin.outstandingLoans": "ബാക്കി വായ്പ",
    "fin.verifiedRecords": "പരിശോധിച്ച രേഖകൾ",
    "fin.physicalCash": "കൈവശമുള്ള പണം",
    "fin.bankBalance": "ബാങ്ക് ബാലൻസ്",
    "fin.reconciled": "പൊരുത്തപ്പെട്ടു",
    "fin.savingsCollected": "സമാഹരിച്ച തുക",
    "cat.contribution": "സാധാരണ നിക്ഷേപം",
    "cat.loan": "വായ്പ",
    "cat.repayment": "വായ്പ തിരിച്ചടവ്",
    "cat.expense": "ചിലവ്",
    "role.member": "അംഗം",
    "role.treasurer": "ട്രഷറർ",
    "role.auditor": "ഓഡിറ്റർ",
    "role.leader": "ഗ്രൂപ്പ് ലീഡർ",
    "status.verified": "പരിശോധിച്ചു",
    "status.pending": "തീർപ്പുകൽപ്പിക്കാത്തത്",
    "status.underReview": "പരിശോധനയിൽ",
    "status.cleared": "പൂർണ്ണമായി തിരിച്ചടച്ചു",
    "status.overdue": "കാലാവധി കഴിഞ്ഞത്",
    "status.matched": "കൃത്യമായി പൊരുത്തപ്പെട്ടു",
    "status.mismatch": "വ്യത്യാസമുണ്ട്",
    "status.closed": "അവസാനിച്ചു",
  },

  gu: {
    "nav.home": "મુખ્ય પૃષ્ઠ",
    "nav.dashboard": "ઝાંખી",
    "nav.transactions": "વ્યવહારો",
    "nav.record": "વોઇસ એન્ટ્રી",
    "nav.loans": "ધિરાણ (લોન)",
    "nav.members": "સભ્યો",
    "nav.approvals": "મંજૂરીઓ",
    "nav.meeting": "મીટિંગ",
    "nav.cashCheck": "રોકડ ચકાસણી",
    "nav.paperImport": "રજીસ્ટર આયાત",
    "nav.verification": "ચકાસણી",
    "nav.disputes": "વિવાદો",
    "nav.reports": "અહેવાલો",
    "nav.timeline": "સમયરેખા",
    "nav.passbook": "પાસબુક",
    "nav.sync": "ઑફલાઇન સિંક",
    "nav.settings": "સેટિંગ્સ",
    "nav.audit": "ઓડિટ ઇતિહાસ",
    "nav.panchasutra": "પંચસૂત્ર",
    "nav.bankPosition": "બેંક અને રોકડ",
    "nav.signOut": "લૉગ આઉટ",
    "nav.viewAs": "રોલ બદલો",
    "app.title": "લેખા (Lekha)",
    "app.groupName": "મા દુર્ગા એસએચજી",
    "app.location": "વારાણસી, યુપી",
    "action.confirm": "પુષ્ટિ કરો અને સાચવો",
    "action.cancel": "રદ કરો",
    "action.continue": "આગળ વધો",
    "action.back": "પાછળ",
    "action.submit": "સબમિટ કરો",
    "action.addTransaction": "+ નવો વ્યવહાર",
    "action.createLoan": "લોન અરજી",
    "action.repay": "હપ્તો જમા કરો",
    "action.viewLedger": "ખાતાવહી જુઓ",
    "action.print": "રસીદ છાપો",
    "action.verify": "ચકાસો",
    "action.closeMeeting": "મીટિંગ પૂર્ણ કરો",
    "action.speak": "સાંભળો",
    "fin.totalCorpus": "કુલ ભંડોળ",
    "fin.balance": "વર્તમાન સિલક",
    "fin.totalContributions": "કુલ બચત",
    "fin.activeLoans": "ચાલુ લોન",
    "fin.outstandingLoans": "બાકી લોન",
    "fin.verifiedRecords": "ચકાસાયેલ રેકોર્ડ",
    "fin.physicalCash": "હાથ પર રોકડ",
    "fin.bankBalance": "બેંક સિલક",
    "fin.reconciled": "મેળવણી થઈ",
    "fin.savingsCollected": "એકત્રિત બચત",
    "cat.contribution": "નિયમિત બચત",
    "cat.loan": "આંતરિક લોન",
    "cat.repayment": "લોન ચુકવણી",
    "cat.expense": "જૂથ ખર્ચ",
    "role.member": "સભ્ય",
    "role.treasurer": "ખજાનચી",
    "role.auditor": "ઓડિટર",
    "role.leader": "ગ્રુપ લીડર",
    "status.verified": "ચકાસાયેલ",
    "status.pending": "બાકી",
    "status.underReview": "સમીક્ષા હેઠળ",
    "status.cleared": "ચૂકતે થયેલ",
    "status.overdue": "મુદત વીતી ગયેલ",
    "status.matched": "મેચ થયેલ",
    "status.mismatch": "તફાવત",
    "status.closed": "પૂર્ણ",
  },

  or: {
    "nav.home": "ମୁଖ୍ୟ ପୃଷ୍ଠା",
    "nav.dashboard": "ସମୀକ୍ଷା",
    "nav.transactions": "କାରବାର",
    "nav.record": "ଭଏସ୍ ଏଣ୍ଟ୍ରି",
    "nav.loans": "ଋଣ",
    "nav.members": "ସଦସ୍ୟ",
    "nav.approvals": "ଅନୁମୋଦନ",
    "nav.meeting": "ବୈଠକ",
    "nav.cashCheck": "ନଗଦ ଯାଞ୍ଚ",
    "nav.paperImport": "ଖାତା ଆମଦାନୀ",
    "nav.verification": "ଯାଞ୍ଚ",
    "nav.disputes": "ଅଭିଯୋଗ",
    "nav.reports": "ରିପୋର୍ଟ",
    "nav.timeline": "ଟାଇମଲାଇନ",
    "nav.passbook": "ପାସବୁକ",
    "nav.sync": "ଅଫଲାଇନ ସିଙ୍କ",
    "nav.settings": "ସେଟିଂସ",
    "nav.audit": "ଅଡିଟ ଇତିହାସ",
    "nav.panchasutra": "ପଞ୍ଚସୂତ୍ର",
    "nav.bankPosition": "ବ୍ୟାଙ୍କ ଓ ନଗଦ",
    "nav.signOut": "ଲଗଆଉଟ",
    "nav.viewAs": "ଭୂମିକା ବଦଳାନ୍ତୁ",
    "app.title": "ଲେଖା (Lekha)",
    "app.groupName": "ମା ଦୁର୍ଗା ଏସଏଚଜି",
    "app.location": "ବାରାଣସୀ",
    "action.confirm": "ନିଶ୍ଚିତ କରନ୍ତୁ",
    "action.cancel": "ବାତିଲ",
    "action.continue": "ଆଗକୁ",
    "action.back": "ପଛକୁ",
    "action.submit": "ଦାଖଲ କରନ୍ତୁ",
    "action.addTransaction": "+ ନୂଆ କାରବାର",
    "action.createLoan": "ଋଣ ଆବେଦନ",
    "action.repay": "କିସ୍ତି ପୈଠ",
    "action.viewLedger": "ଖାତା ଦେଖନ୍ତୁ",
    "action.print": "ରସିଦ ପ୍ରିଣ୍ଟ",
    "action.verify": "ଯାଞ୍ଚ କରନ୍ତୁ",
    "action.closeMeeting": "ବୈଠକ ଶେଷ କରନ୍ତୁ",
    "action.speak": "ଶୁଣନ୍ତୁ",
    "fin.totalCorpus": "ମୋଟ ପାଣ୍ଠି",
    "fin.balance": "ବର୍ତ୍ତମାନ ବାଲାନ୍ସ",
    "fin.totalContributions": "ମୋଟ ସଞ୍ଚୟ",
    "fin.activeLoans": "ଚାଲୁ ଋଣ",
    "fin.outstandingLoans": "ବକେୟା ଋଣ",
    "fin.verifiedRecords": "ଯାଞ୍ଚ ହୋଇଥିବା ରେକର୍ଡ",
    "fin.physicalCash": "ହାତରେ ଥିବା ନଗଦ",
    "fin.bankBalance": "ବ୍ୟାଙ୍କ ବାଲାନ୍ସ",
    "fin.reconciled": "ମିଳିତ",
    "fin.savingsCollected": "ସଂଗୃହିତ ସଞ୍ଚୟ",
    "cat.contribution": "ନିୟମିତ ସଞ୍ଚୟ",
    "cat.loan": "ଋଣ",
    "cat.repayment": "ଋଣ ପରିଶୋଧ",
    "cat.expense": "ଖର୍ଚ୍ଚ",
    "role.member": "ସଦସ୍ୟା",
    "role.treasurer": "କୋଷାଧ୍ୟକ୍ଷ",
    "role.auditor": "ଅଡିଟର",
    "role.leader": "ନେତ୍ରୀ",
    "status.verified": "ଯାଞ୍ଚ ହୋଇଛି",
    "status.pending": "ବାକି ଅଛି",
    "status.underReview": "ସମୀକ୍ଷା ଚାଲିଛି",
    "status.cleared": "ପରିଶୋଧିତ",
    "status.overdue": "ସମୟ ବିତିଯାଇଛି",
    "status.matched": "ସମ୍ପୂର୍ଣ୍ଣ ମିଳିତ",
    "status.mismatch": "ଅମେଳ",
    "status.closed": "ବନ୍ଦ",
  },

  pa: {
    "nav.home": "ਮੁੱਖ ਪੰਨਾ",
    "nav.dashboard": "ਸੰਖੇਪ",
    "nav.transactions": "ਲੈਣ-ਦੇਣ",
    "nav.record": "ਆਵਾਜ਼ ਐਂਟਰੀ",
    "nav.loans": "ਕਰਜ਼ੇ",
    "nav.members": "ਮੈਂਬਰ",
    "nav.approvals": "ਪ੍ਰਵਾਨਗੀਆਂ",
    "nav.meeting": "ਮੀਟਿੰਗ",
    "nav.cashCheck": "ਨਕਦ ਜਾਂਚ",
    "nav.paperImport": "ਰਜਿਸਟਰ ਇੰਪੋਰਟ",
    "nav.verification": "ਪੜਤਾਲ",
    "nav.disputes": "ਸ਼ਿਕਾਇਤਾਂ",
    "nav.reports": "ਰਿਪੋਰਟਾਂ",
    "nav.timeline": "ਟਾਈਮਲਾਈਨ",
    "nav.passbook": "ਪਾਸਬੁੱਕ",
    "nav.sync": "ਆਫ਼ਲਾਈਨ ਸਿੰਕ",
    "nav.settings": "ਸੈਟਿੰਗਾਂ",
    "nav.audit": "ਆਡਿਟ ਇਤਿਹਾਸ",
    "nav.panchasutra": "ਪੰਚਸੂਤਰ",
    "nav.bankPosition": "ਬੈਂਕ ਅਤੇ ਨਕਦ",
    "nav.signOut": "ਲਾਗ ਆਉਟ",
    "nav.viewAs": "ਭੂਮਿਕਾ ਬਦਲੋ",
    "app.title": "ਲੇਖਾ (Lekha)",
    "app.groupName": "ਮਾਂ ਦੁਰਗਾ ਐਸ.ਐਚ.ਜੀ",
    "app.location": "ਵਾਰਾਣਸੀ",
    "action.confirm": "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "action.cancel": "ਰੱਦ ਕਰੋ",
    "action.continue": "ਅੱਗੇ ਵਧੋ",
    "action.back": "ਪਿੱਛੇ",
    "action.submit": "ਜਮ੍ਹਾ ਕਰੋ",
    "action.addTransaction": "+ ਨਵਾਂ ਲੈਣ-ਦੇਣ",
    "action.createLoan": "ਕਰਜ਼ਾ ਅਰਜ਼ੀ",
    "action.repay": "ਕਿਸ਼ਤ ਜਮ੍ਹਾ ਕਰੋ",
    "action.viewLedger": "ਖਾਤਾ ਦੇਖੋ",
    "action.print": "ਰਸੀਦ ਛਾਪੋ",
    "action.verify": "ਜਾਂਚ ਕਰੋ",
    "action.closeMeeting": "ਮੀਟਿੰਗ ਸਮਾਪਤ ਕਰੋ",
    "action.speak": "ਸੁਣੋ",
    "fin.totalCorpus": "ਕੁੱਲ ਫੰਡ",
    "fin.balance": "ਮੌਜੂਦਾ ਬਕਾਇਆ",
    "fin.totalContributions": "ਕੁੱਲ ਬੱਚਤ",
    "fin.activeLoans": "ਚੱਲ ਰਹੇ ਕਰਜ਼ੇ",
    "fin.outstandingLoans": "ਬਕਾਇਆ ਕਰਜ਼ਾ",
    "fin.verifiedRecords": "ਪ੍ਰਮਾਣਿਤ ਰਿਕਾਰਡ",
    "fin.physicalCash": "ਹੱਥ ਵਿੱਚ ਨਕਦੀ",
    "fin.bankBalance": "ਬੈਂਕ ਬਕਾਇਆ",
    "fin.reconciled": "ਮਿਲਾਣ ਹੋਇਆ",
    "fin.savingsCollected": "ਇਕੱਠੀ ਹੋਈ ਬੱਚਤ",
    "cat.contribution": "ਰੋਜ਼ਾਨਾ ਬੱਚਤ",
    "cat.loan": "ਕਰਜ਼ਾ",
    "cat.repayment": "ਕਰਜ਼ਾ ਵਾਪਸੀ",
    "cat.expense": "ਖਰਚਾ",
    "role.member": "ਮੈਂਬਰ",
    "role.treasurer": "ਖ਼ਜ਼ਾਨਚੀ",
    "role.auditor": "ਆਡੀਟਰ",
    "role.leader": "ਗਰੁੱਪ ਲੀਡਰ",
    "status.verified": "ਪ੍ਰਮਾਣਿਤ",
    "status.pending": "ਬਕਾਇਆ",
    "status.underReview": "ਜਾਂਚ ਅਧੀਨ",
    "status.cleared": "ਨਿਪਟਾਰਾ ਹੋਇਆ",
    "status.overdue": "ਮਿਆਦ ਪੁੱਗੀ",
    "status.matched": "ਬਿਲਕੁਲ ਸਹੀ",
    "status.mismatch": "ਅੰਤਰ ਹੈ",
    "status.closed": "ਬੰਦ",
  },

  bho: {
    "nav.home": "मुख्य पन्ना",
    "nav.dashboard": "लेखाजोखा",
    "nav.transactions": "लेन-देन",
    "nav.record": "आवाज से दर्ज करीं",
    "nav.loans": "करजा",
    "nav.members": "सदस्य लोग",
    "nav.approvals": "मंजूरी",
    "nav.meeting": "बैठक",
    "nav.cashCheck": "रोकड़ मिलान",
    "nav.paperImport": "रजिस्टर आयात",
    "nav.verification": "सत्यापन",
    "nav.disputes": "शिकायत",
    "nav.reports": "रिपोर्ट",
    "nav.timeline": "टाइमलाइन",
    "nav.passbook": "पासबुक",
    "nav.sync": "ऑफलाइन सिंक",
    "nav.settings": "सेटिंग",
    "nav.audit": "ऑडिट इतिहास",
    "nav.panchasutra": "पंचसूत्र",
    "nav.bankPosition": "बैंक आ रोकड़",
    "nav.signOut": "लॉग आउट",
    "nav.viewAs": "भूमिका बदलीं",
    "app.title": "लेखा (Lekha)",
    "app.groupName": "माँ दुर्गा समूह",
    "app.location": "वाराणसी",
    "action.confirm": "पुख्ता करीं आ सहेजीं",
    "action.cancel": "रद्द करीं",
    "action.continue": "आगे बढ़ीं",
    "action.back": "पाछे",
    "action.submit": "जमा करीं",
    "action.addTransaction": "+ नया लेन-देन",
    "action.createLoan": "करजा खातिर अर्जी",
    "action.repay": "किस्त भरीं",
    "action.viewLedger": "खाता देखीं",
    "action.print": "रसीद छापीं",
    "action.verify": "जांचीं",
    "action.closeMeeting": "बैठक पूरा करीं",
    "action.speak": "सुनीं",
    "fin.totalCorpus": "कुल जमा पूँजी",
    "fin.balance": "बचत बाकी",
    "fin.totalContributions": "कुल बचत",
    "fin.activeLoans": "चालू करजा",
    "fin.outstandingLoans": "बाकी करजा",
    "fin.verifiedRecords": "जांचल रिकॉर्ड",
    "fin.physicalCash": "हाथ में रोकड़ा",
    "fin.bankBalance": "बैंक में बाकी",
    "fin.reconciled": "मिलान भइल",
    "fin.savingsCollected": "जमा बचत",
    "cat.contribution": "नियमित बचत",
    "cat.loan": "समूह करजा",
    "cat.repayment": "करजा वापसी",
    "cat.expense": "समूह के खर्चा",
    "role.member": "सदस्य",
    "role.treasurer": "खजांची",
    "role.auditor": "ऑडिटर",
    "role.leader": "लीडर",
    "status.verified": "जांचल गइल",
    "status.pending": "बाकी",
    "status.underReview": "जांच चल रहल बा",
    "status.cleared": "पूरा चुकता",
    "status.overdue": "तय समय से देरी",
    "status.matched": "एकदम सही मिलल",
    "status.mismatch": "अंतर बा",
    "status.closed": "बंद भइल",
  },

  mai: {
    "nav.home": "मुख्य पृष्ठ",
    "nav.dashboard": "सारांश",
    "nav.transactions": "लेन-देन",
    "nav.record": "आवाज सं प्रविष्टि",
    "nav.loans": "ऋण",
    "nav.members": "सदस्य",
    "nav.approvals": "मंजूरी",
    "nav.meeting": "बैठक",
    "nav.cashCheck": "रोकड़ मिलान",
    "nav.paperImport": "रजिस्टर आयात",
    "nav.verification": "सत्यापन",
    "nav.disputes": "विवाद",
    "nav.reports": "रिपोर्ट",
    "nav.timeline": "टाइमलाइन",
    "nav.passbook": "पासबुक",
    "nav.sync": "ऑफलाइन सिंक",
    "nav.settings": "सेटिंग",
    "nav.audit": "ऑडिट इतिहास",
    "nav.panchasutra": "पंचसूत्र",
    "nav.bankPosition": "बैंक ओ रोकड़",
    "nav.signOut": "लॉग आउट",
    "nav.viewAs": "भूमिका बदलू",
    "app.title": "लेखा (Lekha)",
    "app.groupName": "माँ दुर्गा स्वयं सहायता समूह",
    "app.location": "वाराणसी",
    "action.confirm": "पुष्टि करू ओ सुरक्षित करू",
    "action.cancel": "रद्द करू",
    "action.continue": "आगे बढ़ू",
    "action.back": "पाछा",
    "action.submit": "जमा करू",
    "action.addTransaction": "+ नव लेन-देन",
    "action.createLoan": "ऋण लेबाक आवेदन",
    "action.repay": "किस्त जमा करू",
    "action.viewLedger": "खाता देखू",
    "action.print": "रसीद छापू",
    "action.verify": "जाँच करू",
    "action.closeMeeting": "बैठक समाप्त करू",
    "action.speak": "सुनू",
    "fin.totalCorpus": "कुल समूह कोष",
    "fin.balance": "वर्तमान शेष",
    "fin.totalContributions": "कुल बचत",
    "fin.activeLoans": "सक्रिय ऋण",
    "fin.outstandingLoans": "बाकी ऋण राशि",
    "fin.verifiedRecords": "सत्यापित रिकॉर्ड",
    "fin.physicalCash": "हाथ में नकद",
    "fin.bankBalance": "बैंक खाता शेष",
    "fin.reconciled": "मिलान भेल",
    "fin.savingsCollected": "जमा बचत",
    "cat.contribution": "नियमित बचत",
    "cat.loan": "समूह ऋण",
    "cat.repayment": "ऋण वापसी",
    "cat.expense": "समूह खर्च",
    "role.member": "सदस्य",
    "role.treasurer": "कोषाध्यक्ष",
    "role.auditor": "ऑडिटर",
    "role.leader": "समूह नेत्री",
    "status.verified": "सत्यापित",
    "status.pending": "लंबित",
    "status.underReview": "जाँच चलि रहल अछि",
    "status.cleared": "पूर्ण चुकता",
    "status.overdue": "विलंबित",
    "status.matched": "सटीक मिलान",
    "status.mismatch": "अंतर अछि",
    "status.closed": "बंद भेल",
  },
};

interface LanguageContextValue {
  language: LanguageCode;
  languageOption: LanguageOption;
  setLanguage: (code: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLangState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem("ps18_app_lang") as LanguageCode;
      if (saved && TRANSLATIONS[saved]) return saved;
    } catch {}
    return "hi"; // Default to Hindi
  });

  const setLanguage = (code: LanguageCode) => {
    if (TRANSLATIONS[code]) {
      setLangState(code);
      try {
        localStorage.setItem("ps18_app_lang", code);
      } catch {}
    }
  };

  const languageOption = SUPPORTED_LANGUAGES.find((l) => l.code === language) || SUPPORTED_LANGUAGES[0];

  const t = (key: string, defaultText?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const enDict = TRANSLATIONS.en;
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, languageOption, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
